### ISSUE TITLE
Create binary distributions for common platforms (e.g. wheels)

### ISSUE THREAD

**Issue by chad-earthscope** [EarthScope/mseedlib#6]
Initial plan was to use:
https://cibuildwheel.pypa.io/en/stable/

with github actions.

**Comment by chad-earthscope** [comment]
Suggested target platforms:

- linux x86_64
- linux arm64
- macos x86_64
- macos arm64
- windows x6_64

**Comment by mbriggs134** [comment]
Confirmed the artifacts are visible to everyone.   Also got Windows and mac builds working.

Below is the latest.  Next step is to test these binaries.
https://github.com/mbriggs134/mseedlib/actions/runs/9214543683

**Comment by mbriggs134** [comment]
Needed to emulation (QEMU) to actions for Linux arm64 target:
https://github.com/mbriggs134/mseedlib/actions/runs/9257825394

Checked:
- Windows amd64 (windows 10 / python 3.9)
- Mac 14 (M2 processor / OS14.4 / python 3.12
- ManyLinux (x86_64 / Amazon Linux 2023 / python 3.9, 3.11)
- ManyLinux (arm64 [aarch64] / Amazon Linux 2023.4.20240513 / python 3.11)

@chad-earthscope 
Anything else before a PR like streamlining pypy submission?

**Comment by chad-earthscope** [comment]
Done with v0.0.5 release.
